/**
 * @author Nathan Sweet <misc at n4te.com>
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_scintilla_editor_Scintilla */

#ifndef _Included_org_scintilla_editor_Scintilla
#define _Included_org_scintilla_editor_Scintilla
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_scintilla_editor_Scintilla
 * Method:    createControl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_scintilla_editor_Scintilla_createControl
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_scintilla_editor_Scintilla
 * Method:    resizeControl
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_org_scintilla_editor_Scintilla_resizeControl
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     org_scintilla_editor_Scintilla
 * Method:    setFocus
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_scintilla_editor_Scintilla_setFocus
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_scintilla_editor_Scintilla
 * Method:    sendMessage
 * Signature: (IILorg/scintilla/editor/CText;)I
 */
JNIEXPORT jint JNICALL Java_org_scintilla_editor_Scintilla_sendMessage__IILorg_scintilla_editor_CText_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     org_scintilla_editor_Scintilla
 * Method:    sendMessage
 * Signature: (IILorg/scintilla/editor/TextRange;)I
 */
JNIEXPORT jint JNICALL Java_org_scintilla_editor_Scintilla_sendMessage__IILorg_scintilla_editor_TextRange_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     org_scintilla_editor_Scintilla
 * Method:    sendMessage
 * Signature: (IILorg/scintilla/editor/FindText;)I
 */
JNIEXPORT jint JNICALL Java_org_scintilla_editor_Scintilla_sendMessage__IILorg_scintilla_editor_FindText_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     org_scintilla_editor_Scintilla
 * Method:    sendMessage
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_scintilla_editor_Scintilla_sendMessage__III
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_scintilla_editor_Scintilla
 * Method:    sendMessage
 * Signature: (IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_scintilla_editor_Scintilla_sendMessage__IILjava_lang_String_2
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     org_scintilla_editor_Scintilla
 * Method:    sendMessage
 * Signature: (ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_scintilla_editor_Scintilla_sendMessage__ILjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
